### ISSUE TITLE
Presenter has not been initialized

### ISSUE THREAD

**Issue by AzimshokhNematov** [moxy-community/Moxy#133]
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {......UserAuthenticationActivity}: kotlin.UninitializedPropertyAccessException: lateinit property userAuthenticationPresenter has not been initialized
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4225)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4327)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3426)
       at android.app.ActivityThread.access$1100(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7406)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
       
       
Hi, Moxy library team!

I am using your library in my current project. However I am not able to resolve some of the bugs. I have shown the nature of the problem above. 

This bug is observed only on Android SDK 23 version and only on Samsung devices. Could you please help with this problem? Thanks.

**Comment by alaershov** [comment]
Hi there! 

Please share the code of your Presenter, Activity and Gradle config via [Gist](https://gist.github.com), of just share an entire project repository.

Also make sure you're using the latest Moxy version.

**Comment by AzimshokhNematov** [comment]
Hi
Activity, Presenter and gradle config [gist](https://gist.github.com/AzimshokhNematov/d2c7d8f6c234cb17e0ac4bad36815e4d) 
moxy version 2.2.1

thanks.

**Comment by alaershov** [comment]
Well, I don't see anything too suspicious. Maybe it has something to do with fingerprint auth on Samsung, but I'm afraid we can't help you much, the bug is device-specific and may happen because of a bug in Samsung version of Android.

**Comment by AzimshokhNematov** [comment]
okay Thank you Bro.

Good job
