### ISSUE TITLE
Kotlin 2.0.0 + Hilt supporting

### ISSUE THREAD

**Issue by IvanMikhayluts** [moxy-community/Moxy#144]
Unfortunately kotlin 2.0.0 + Hilt is not supported now.
When trying to build gradle throws error:
```
Unable to read Kotlin metadata due to unsupported metadata version.: java.lang.IllegalStateException: Unable to read Kotlin metadata due to unsupported metadata version.
  	at dagger.hilt.processor.internal.kotlin.KotlinMetadata.metadataOf(KotlinMetadata.java:206)
  	at dagger.hilt.processor.internal.kotlin.KotlinMetadata.from(KotlinMetadata.java:187)
  	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
  	at dagger.hilt.processor.internal.kotlin.KotlinMetadataFactory.create(KotlinMetadataFactory.java:57)
  	at dagger.hilt.processor.internal.kotlin.KotlinMetadataFactory.create(KotlinMetadataFactory.java:68)
  	at dagger.hilt.processor.internal.kotlin.KotlinMetadataUtil.containsConstructorWithDefaultParam(KotlinMetadataUtil.java:215)
Unable to read Kotlin metadata due to unsupported metadata version.
```
I don't check whether supports kotlin 2.0.0 without hilt. I assume that the problems will remain.

**Comment by romankulykov** [comment]
Try to update hilt version to 2.55
